"""Is `gen_themes.py` still the thing that produced `app/panel/themes/`?

WHY THIS EXISTS. The five theme CSS files carry a header that says "GENERATED by
`_main/_design-lane/gen_themes.py`. Do not hand-edit." Before editing that header I
have to know whether regenerating would CLOBBER hand-edits somebody made after the
last generation run. A generator that no longer reproduces its own output is a trap,
not a tool.

METHOD. Import the generator, point its `OUT` at a temp dir, rebuild all five, then
compare sha256 of temp vs disk. Writes its verdict to a file as well as stdout,
because it is launched with `pythonw.exe` (this repo forbids a visible console).

READ-ONLY with respect to the repo: it never writes into `app/panel/themes/`.
"""
import hashlib
import importlib.util
import io
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, os.pardir))
GEN = os.path.join(HERE, '_design-lane', 'gen_themes.py')
DISK = os.path.join(ROOT, 'app', 'panel', 'themes')
REPORT = os.path.join(HERE, '_theme-gen-dryrun.txt')

out = io.StringIO()


def say(line=''):
    out.write(line + '\n')
    print(line)


def sha(path):
    with open(path, 'rb') as fh:
        return hashlib.sha256(fh.read()).hexdigest().upper()


def main():
    spec = importlib.util.spec_from_file_location('gen_themes', GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    say('GEN     %s' % GEN)
    say('GEN sha %s' % sha(GEN))
    say('DISK    %s' % DISK)
    say('')

    tmp = tempfile.mkdtemp(prefix='theme-gen-dryrun-')
    mod.OUT = tmp
    mod.main()
    say('')

    mismatches = []
    missing = []
    for t in mod.THEMES:
        name = 'theme-%d.css' % t['n']
        a = os.path.join(tmp, name)
        b = os.path.join(DISK, name)
        if not os.path.exists(b):
            missing.append(name)
            say('%-14s DISK FILE ABSENT' % name)
            continue
        sa, sb = sha(a), sha(b)
        ba = os.path.getsize(a)
        bb = os.path.getsize(b)
        same = (sa == sb)
        say('%-14s generated %7d B %s' % (name, ba, sa[:16]))
        say('%-14s on disk   %7d B %s   %s' % ('', bb, sb[:16], 'IDENTICAL' if same else 'DIFFERS'))
        if not same:
            # A delta of exactly +1 byte per line is CRLF vs LF and nothing else.
            # Normalise and re-compare, so "DIFFERS" can be split into
            # "whitespace-only, generator is still the author" vs "real drift".
            with open(a, 'rb') as fh:
                ga = fh.read()
            with open(b, 'rb') as fh:
                gb = fh.read()
            gb_lf = gb.replace(b'\r\n', b'\n')
            crlf = gb.count(b'\r\n')
            bare_lf = len(gb) - crlf * 2 - (len(gb) - len(gb.replace(b'\n', b'\n')))
            say('%-14s disk CRLF=%d   delta=%+d bytes (%+d per line)'
                % ('', crlf, bb - ba, (bb - ba) // max(1, ga.count(b'\n'))))
            if gb_lf == ga:
                say('%-14s NORMALISED IDENTICAL - the ONLY difference is CRLF; the generator '
                    'is still the author of every byte' % '')
            else:
                mismatches.append(name)
                # Show the first differing line, which is what a real hand-edit looks like.
                la, lb = ga.split(b'\n'), gb_lf.split(b'\n')
                for i, (x, y) in enumerate(zip(la, lb), 1):
                    if x != y:
                        say('%-14s first real difference at line %d:' % ('', i))
                        say('%-14s   generated: %s' % ('', x[:120]))
                        say('%-14s   on disk  : %s' % ('', y[:120]))
                        break
                if len(la) != len(lb):
                    say('%-14s line count differs: generated %d, on disk %d'
                        % ('', len(la), len(lb)))

    say('')
    if missing:
        say('VERDICT: RED - generator cannot reproduce %s (absent on disk)' % missing)
        return 1
    if mismatches:
        say('VERDICT: RED - %d file(s) differ; regenerating WOULD clobber them: %s'
            % (len(mismatches), mismatches))
        return 1
    say('VERDICT: GREEN - the generator reproduces all 5 files byte for byte; '
        'regenerating is safe and no hand-edit exists to lose')
    return 0


if __name__ == '__main__':
    rc = main()
    with open(REPORT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(out.getvalue())
    sys.exit(rc)
