"""Does gen_themes.py still reproduce app/panel/themes, and is the ONLY
difference the change we meant to make?

Why this exists next to _theme-gen-dryrun.py: that instrument reads the disk
file in TEXT mode with universal newlines, so every CRLF in the on-disk file
becomes a bare LF in memory, and it then compares that string against the
generated BYTES. The mismatch it reports ("delta=-N bytes, -1 or -2 per line")
is therefore an artefact of the comparison, not a property of the files. It
printed a phantom -2/line while the real difference was exactly the intended
prose. This script compares raw BYTES to raw BYTES, and only then normalises
line endings to show the line-level diff, so a reader can attribute every
changed line to a change that was actually made.

Read-only with respect to the repo: the generator's OUT is pointed at a temp
directory, so app/panel/themes is never written.
"""
import hashlib
import importlib.util
import os
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, os.pardir))
GEN = os.path.join(HERE, '_design-lane', 'gen_themes.py')
DISK = os.path.join(REPO, 'app', 'panel', 'themes')
THEMES = ['theme-%d.css' % n for n in range(1, 6)]


def endings(raw):
    """(CRLF count, bare LF count) - a bare LF is an LF with no CR before it."""
    crlf = lf = 0
    for i, b in enumerate(raw):
        if b == 0x0A:
            if i and raw[i - 1] == 0x0D:
                crlf += 1
            else:
                lf += 1
    return crlf, lf


def load(path):
    spec = importlib.util.spec_from_file_location('gen_themes_subject', path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def diff_hunks(a, b, ctx=2, max_hunks=40):
    """a = disk lines, b = generated lines, both with line endings normalised to
    LF. Returns a list of rendered hunks for the mismatching regions."""
    import difflib
    out = []
    sm = difflib.SequenceMatcher(None, a, b, autojunk=False)
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == 'equal':
            continue
        pre = a[max(0, i1 - ctx):i1]
        post = a[i2:i2 + ctx]
        block = []
        for k, line in enumerate(pre):
            block.append('   %5d | %s' % (max(0, i1 - ctx) + k + 1, line))
        for k, line in enumerate(a[i1:i2]):
            block.append(' - %5d | %s' % (i1 + k + 1, line))
        for k, line in enumerate(b[j1:j2]):
            block.append(' + %5d | %s' % (j1 + k + 1, line))
        for k, line in enumerate(post):
            block.append('   %5d | %s' % (i2 + k + 1, line))
        out.append('%s  disk[%d:%d] -> gen[%d:%d]  (%d removed / %d added)\n%s'
                   % (tag.upper(), i1 + 1, i2, j1 + 1, j2, i2 - i1, j2 - j1,
                      '\n'.join(block)))
        if len(out) >= max_hunks:
            out.append('... more hunks suppressed (max_hunks=%d)' % max_hunks)
            break
    return out


def main():
    print('GEN     %s' % GEN)
    print('GEN sha %s' % hashlib.sha256(open(GEN, 'rb').read()).hexdigest().upper())
    print('DISK    %s' % DISK)

    mod = load(GEN)
    tmp = tempfile.mkdtemp(prefix='theme-gen-verify-')
    mod.OUT = tmp
    mod.main()
    print('')

    total_hunks = 0
    verdict_rows = []
    for name in THEMES:
        gpath = os.path.join(tmp, name)
        dpath = os.path.join(DISK, name)
        graw = open(gpath, 'rb').read()
        draw = open(dpath, 'rb').read()
        g_crlf, g_lf = endings(graw)
        d_crlf, d_lf = endings(draw)

        gsha = hashlib.sha256(graw).hexdigest().upper()[:16]
        dsha = hashlib.sha256(draw).hexdigest().upper()[:16]
        same_bytes = graw == draw

        # Normalise CRLF -> LF on BOTH sides, then compare line lists.
        gl = graw.replace(b'\r\n', b'\n').decode('utf-8').split('\n')
        dl = draw.replace(b'\r\n', b'\n').decode('utf-8').split('\n')
        hunks = diff_hunks(dl, gl)
        total_hunks += len(hunks)

        print('%-14s gen %6d B %s  CRLF=%-4d bareLF=%-3d  %d lines'
              % (name, len(graw), gsha, g_crlf, g_lf, len(gl)))
        print('%-14s disk %6d B %s  CRLF=%-4d bareLF=%-3d  %d lines'
              % ('', len(draw), dsha, d_crlf, d_lf, len(dl)))
        if same_bytes:
            print('               BYTE-IDENTICAL to disk\n')
            verdict_rows.append((name, 'identical'))
            continue
        if not hunks:
            print('               line-identical after CRLF normalisation')
            print('               -> the ONLY difference is line endings\n')
            verdict_rows.append((name, 'endings-only'))
            continue
        print('               NORMALISED LINE DIFF: %d hunk(s)' % len(hunks))
        for h in hunks:
            print(h)
        print('')
        verdict_rows.append((name, '%d hunk(s)' % len(hunks)))

    print('=' * 72)
    for name, what in verdict_rows:
        print('  %-14s %s' % (name, what))
    print('=' * 72)
    print('Every hunk above must be attributable to gen_themes.py prose or the')
    print('reduced-motion selector narrowing. An unattributable hunk is a RED.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
