"""One-off surgery on `build_fonts.py`: replace everything from `def main():` to
end of file with the multi-family version (16 families, italic faces).

WHY A PATCH SCRIPT AND NOT AN EDITOR: `main()` contains em dashes inside string
literals, and a literal-match edit against those has already failed once in this
lane. This file is pure ASCII (the em dashes are `\\u2014` escapes), and it
ASSERTS the anchor is unique before touching anything, so a drifted file makes it
refuse instead of mangling.
"""

import io
import os
import sys

TARGET = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'build_fonts.py')
ANCHOR = 'def main():'

NEW_MAIN = '''def main():
    if not os.path.isdir(SIDE):
        hint = ('  cd app/panel/_fonts && npm install '
                + ' '.join('@fontsource/' + pkg for _, pkg, _, _ in FAMILIES)
                + ' --no-audit --no-fund')
        print('MISSING: %s \\u2014 install the packs first:\\n%s' % (SIDE, hint),
              file=sys.stderr)
        return 2

    os.makedirs(FONTS_OUT, exist_ok=True)
    os.makedirs(os.path.dirname(CSS_OUT), exist_ok=True)

    missing = []
    blocks = []
    total = 0
    for family, pkg, weights, italics in FAMILIES:
        rng = unicode_range(pkg)
        # One face per (weight, style): `normal` always, `italic` only where a
        # design asks for it. The family's `unicode-range` is read once and is
        # the same for every face of that family.
        faces = [(w, 'normal') for w in weights] + [(w, 'italic') for w in italics]
        for weight, style in faces:
            src = source_file(pkg, weight, style)
            if not src:
                missing.append('%s %d %s' % (family, weight, style))
                continue
            name = '%s-%s-%d-%s.woff2' % (pkg, SUBSET, weight, style)
            dst = os.path.join(FONTS_OUT, name)
            shutil.copyfile(src, dst)
            size = os.path.getsize(dst)
            total += size
            blocks.append(
                "/* %s %d %s \\u2014 %s, %d B */\\n"
                '@font-face {\\n'
                "  font-family: '%s';\\n"
                '  font-style: %s;\\n'
                '  font-weight: %d;\\n'
                '  font-display: swap;\\n'
                "  src: url(../fonts/%s) format('woff2');\\n"
                '  unicode-range: %s;\\n'
                '}\\n' % (family, weight, style, pkg, size, family, style, weight,
                          name, rng))

    if missing:
        print('MISSING font files: %s' % ', '.join(missing), file=sys.stderr)
        return 1

    header = (
        '/* Sotto \\u2014 THE BUNDLED TYPEFACES OF THE DESIGN DIRECTIONS AND OF THE\\n'
        ' * `cinematic` TEMPLATE SET.\\n'
        ' *\\n'
        ' * GENERATED by `_main/_design-lane/build_fonts.py`. Do not hand-edit.\\n'
        ' *\\n'
        ' * Linked by `panel.html` BEFORE `panel.css`, once for EVERY theme: an\\n'
        ' * `@font-face` has no selector, paints nothing and declares no colour, so\\n'
        ' * it cannot collide with a theme. Each theme then NAMES one of these\\n'
        ' * families in its `--font-sans` / `--font-mono` token.\\n'
        ' *\\n'
        ' * THE OWNER ASKED FOR ALL OF THEM, verbatim (2026-10-08): *"eu gostei de\\n'
        ' * todas as fontes, entao inclua toda as fontes"* \\u2014 the sixteen families\\n'
        ' * the design zips name. %d faces, %.1f KB, latin only (U+0000-00FF): that\\n'
        ' * is where Portuguese lives, a/o/c with tilde/cedilla all below U+0100.\\n'
        ' * Weight AND italic are bundled only where a design asks for them, which\\n'
        ' * is what keeps this near 1 MB instead of the sixteen whole packages.\\n'
        ' *\\n'
        ' * LICENCES (all redistributable, all require attribution \\u2014 see\\n'
        ' * `fonts/LICENSE-NOTES.md`): all sixteen families are SIL OFL 1.1.\\n'
        ' */\\n\\n' % (len(blocks), total / 1024.0))

    with open(CSS_OUT, 'w', encoding='utf-8', newline='\\n') as fh:
        fh.write(header + '\\n'.join(blocks))

    for family, pkg, weights, italics in FAMILIES:
        print('%-20s normal=[%s] italic=[%s]'
              % (family, ' '.join(str(w) for w in weights),
                 ' '.join(str(w) for w in italics)))
    print('wrote %d @font-face block(s) -> %s' % (len(blocks), CSS_OUT))
    print('copied %d file(s), %.1f KB -> %s' % (len(blocks), total / 1024.0, FONTS_OUT))
    return 0


if __name__ == '__main__':
    sys.exit(main())
'''


def main():
    with io.open(TARGET, encoding='utf-8') as fh:
        src = fh.read()

    n = src.count(ANCHOR)
    if n != 1:
        print('REFUSED: %r appears %d times in %s (expected exactly 1)'
              % (ANCHOR, n, TARGET), file=sys.stderr)
        return 1

    head = src[:src.index(ANCHOR)]
    out = head + NEW_MAIN
    if out == src:
        print('REFUSED: no change', file=sys.stderr)
        return 1

    with io.open(TARGET, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(out)

    print('patched %s: %d -> %d bytes' % (TARGET, len(src), len(out)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
