"""WORKER 2 -- revive the interrupted lane 'Receipts + decisions sweep' (pair).

Evidence that these two lanes died: local_runtime_sessions, workspace
I:\\!aicompanion, status='interrupted', updated_at=2026-10-06 21:33:12, children of
root mvs_a4ac79cd2b11453d8e647c4bee2539f5, titles:
  - "Receipts + decisions sweep"
  - "TODO sweep aicompanion"

Their residue: the repo has UNCOMMITTED work on branch wip/recover-2026-10-05 and
several loose files in the root that no lane committed. This worker produces a
SHA256 INVENTORY of that uncommitted residue, so nothing can be lost silently,
and names the deleted file the fence left behind.

HARD RULE honoured: "Never delete an untracked file without a sha256 backup."
This worker deletes nothing. It BACKS UP the inventory, and reports the one file
git reports as deleted (D ci-verify-full.txt) as a finding for a human.

FORBIDDEN (hard): git add -A, git checkout, git reset, git restore, any build,
any write outside the single receipt + inventory path below.

Exit codes are contracts: 0 = inventory written, 2 = could not verify.
"""
from __future__ import annotations

import hashlib
import pathlib
import subprocess
import sys

REPO = pathlib.Path(r"I:\!aicompanion")
INV = REPO / "receipts" / "uncommitted-inventory.sha256"
OUT = REPO / "receipts" / "receipt-aicomp-02-todo-sweep-lane.md"


def git(*args: str) -> str:
    r = subprocess.run(["git", "-C", str(REPO), *args],
                       capture_output=True, text=True, timeout=180)
    return (r.stdout or "") + (r.stderr or "")


def sha256_file(p: pathlib.Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    if not (REPO / ".git").exists():
        print("FAIL: not a git repo")
        return 2
    status = git("status", "--porcelain")
    if not status.strip():
        print("note: worktree clean -- nothing to inventory")
    rows = []
    for line in status.splitlines():
        if len(line) < 4:
            continue
        code, rel = line[:2], line[3:].strip().strip('"')
        p = REPO / rel
        if p.is_file():
            rows.append((code, rel, p.stat().st_size, sha256_file(p)))
        else:
            rows.append((code, rel, -1, "DELETED-OR-NOT-A-FILE"))
    tracked = {r[1] for r in rows}
    loose = sorted(p.name for p in REPO.glob("*.*")
                   if p.is_file() and p.name not in tracked
                   and p.name not in {"package.json", "package-lock.json",
                                      "AGENTS.md", "VERSIONS.txt", ".gitignore"}
                   and not p.name.startswith("."))
    loose_rows = [(n, (REPO / n).stat().st_size, sha256_file(REPO / n))
                  for n in loose if (REPO / n).is_file()]

    INV.parent.mkdir(parents=True, exist_ok=True)
    body = ["# sha256 inventory of UNCOMMITTED residue on wip/recover-2026-10-05",
            "# generated by seat aicompanion worker-2; read-only census, nothing deleted",
            f"# git status --porcelain at generation time: {len(rows)} entries"]
    for code, rel, size, digest in rows:
        body.append(f"{digest}  {code} {rel}  {size}")
    for name, size, digest in loose_rows:
        body.append(f"{digest}  ?? {name}  {size}")
    INV.write_text("\n".join(body) + "\n", encoding="utf-8")

    deleted = [r for r in rows if r[3] == "DELETED-OR-NOT-A-FILE"]
    lines = [
        "# receipt-aicomp-02 -- the interrupted 'Receipts + decisions sweep' lanes",
        "",
        "Two lanes died together: 'Receipts + decisions sweep' and "
        "'TODO sweep aicompanion', both status='interrupted' at 2026-10-06 "
        "21:33:12 under root mvs_a4ac79cd (MEASURED, local_runtime_sessions).",
        "",
        "## Verdict",
        "",
        f"Uncommitted residue present: **{len(rows)}** entries in `git status`.",
        f"Untracked loose files in repo root: **{len(loose_rows)}**.",
        f"Entries git reports as deleted: **{len(deleted)}** -> "
        f"{[d[1] for d in deleted] or 'none'}.",
        "",
        "## What this worker did NOT do",
        "",
        "- Did NOT restore or delete any file. The deleted entries above are a "
        "FINDING for a human, not this worker's call.",
        "- Did NOT run `git add -A`, `git checkout`, `git reset`, `git restore`.",
        "- Did NOT run any build.",
        "",
        "## Safety net written",
        "",
        f"`{INV.name}` -- sha256 of every uncommitted/untracked file above, so "
        "the residue is recoverable even if a later lane clobbers it.",
        "",
        "## Inventory",
        "",
        "| code | path | bytes |",
        "|---|---|---:|",
    ]
    for code, rel, size, _ in rows:
        lines.append(f"| `{code}` | `{rel}` | {size} |")
    lines += ["", "| untracked root file | bytes |", "|---|---:|"]
    for name, size, _ in loose_rows:
        lines.append(f"| `{name}` | {size} |")
    lines += [
        "",
        "## UNKNOWN (named, not guessed)",
        "",
        "- Whether the uncommitted diff is correct or half-finished.",
        "- Whether the deleted file(s) were meant to be deleted.",
        "- Whether the fence left anything recoverable that is not on disk.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"status_entries={len(rows)} untracked_root={len(loose_rows)} "
          f"deleted={len(deleted)}")
    print(f"inventory={INV} bytes={INV.stat().st_size}")
    print(f"receipt={OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())