/* Sotto — the theme MANIFEST.
 *
 * WHY THIS IS A SCRIPT AND NOT A JSON FILE, AND WHY IT IS NOT `fetch`ed:
 * the panel runs over `file://`, and `fetch()` of a `file://` URL is refused by
 * Chromium. It is ALSO refused without a network round trip under the panel's
 * own CSP (`default-src 'none'`). A `<script src="themes/themes.js">` is allowed
 * by `script-src 'self'`, loads synchronously in document order, and gives
 * `theme-switcher.js` the list before any theme has to exist. So the manifest is
 * ONE plain object literal, readable by a human and by a script, and the
 * switcher has no I/O at all.
 *
 * THE FIVE NAMES ARE THE OWNER'S FIVE DESIGN DIRECTIONS, in his own order, and
 * each entry is the direction's own accent from
 * `H:\aireplay\docs\design\sotto-app-design-directions\src\data\designs.ts`:
 *
 *   1 Teleprompter  tele   #f2e9d8  Barlow Condensed
 *   2 Broadcast     bcast  #ff6a55  IBM Plex Mono
 *   3 Manuscrito    mano   #a9c1d9  Newsreader
 *   4 Cinema Card   cine   #e4b363  Fraunces
 *   5 Instrumento   inst   #5fd3a7  Space Grotesk
 *
 * `name` is the id in `document.documentElement.dataset.theme`, i.e. the
 * `theme-N` of `themes/theme-N.css` and the value every rule in those files is
 * scoped to. `label` is what the in-panel button and the picker show, and it is
 * the DIRECTION's name — a theme is a design here, not a colour scheme, and the
 * owner has to be able to read which direction he is looking at. `swatch` must
 * equal that theme's `--accent`, or the dot on the button lies about the theme
 * it is offering; the five accents above are what `gen_themes.py` writes into
 * those files, and `_main/_theme-probe-arm.py` checks the two agree — per theme,
 * against the direction's own accent in `designs.ts` (the manifest is read out of
 * the live document and compared with `EXPECTED`, so a swatch that drifts from
 * its theme goes RED). (This comment used to name `_main/_theme-styles-oracle.js`,
 * which does not exist — the check lives in the probe.)
 *
 *
 *
 *
 * THE TEMPLATE SET (added 2026-10-08, owner: *"gostei de alguns designs que botei
 * ai no workspace… eu quero uma mudança mesmo, a cada tema/template"*). Every entry
 * below the five carries its own `file` — `themes/cinematic.css`, one generated
 * document holding the whole set — and may carry `group`/`groupLabel`/`variant`,
 * which is what makes a near-duplicate pair visible AS a pair in the picker instead
 * of two unrelated names. `group` is the A/B/C family, `variant` is the letter, and
 * `groupLabel` is written only on the FIRST member of a group. All three are
 * rendered by `theme-switcher.js` and none of them decides anything about the
 * design. This file is REGENERATED by `_main/_design-lane/gen_cinematic.py`, which
 * reads the five entries above out of it verbatim — so the five are never retyped,
 * and their swatches cannot drift from what `gen_themes.py` writes into their CSS.
 */
(function (root) {
  'use strict';

  var THEMES = [
    {
      name: 'theme-1',
      label: 'Teleprompter',
      file: 'themes/theme-1.css',
      swatch: '#f2e9d8'
    },
    {
      name: 'theme-2',
      label: 'Broadcast',
      file: 'themes/theme-2.css',
      swatch: '#ff6a55'
    },
    {
      name: 'theme-3',
      label: 'Manuscrito',
      file: 'themes/theme-3.css',
      swatch: '#a9c1d9'
    },
    {
      name: 'theme-4',
      label: 'Cinema Card',
      file: 'themes/theme-4.css',
      swatch: '#e4b363'
    },
    {
      name: 'theme-5',
      label: 'Instrumento',
      file: 'themes/theme-5.css',
      swatch: '#5fd3a7'
    },
    {
      name: 'cine-midnight-rain',
      label: 'Midnight Rain',
      file: 'themes/cinematic.css',
      swatch: '#7fb3dc'
    },
    {
      name: 'cine-warm-hour',
      label: 'The Warm Hour',
      file: 'themes/cinematic.css',
      swatch: '#e0a35f'
    },
    {
      name: 'cine-velvet-dusk',
      label: 'Velvet Dusk',
      file: 'themes/cinematic.css',
      swatch: '#d18cb2'
    },
    {
      name: 'cine-study-light',
      label: 'Study Light',
      file: 'themes/cinematic.css',
      swatch: '#d9a45f'
    },
    {
      name: 'cine-tideline-body',
      label: 'Tideline',
      file: 'themes/cinematic.css',
      swatch: '#63bfb2',
      group: 'abc-rain-body',
      groupLabel: 'A/B: o mesmo corpo, duas paletas',
      variant: 'A'
    },
    {
      name: 'cine-north-fog',
      label: 'North Fog',
      file: 'themes/cinematic.css',
      swatch: '#7fbb9c',
      group: 'abc-rain-body',
      variant: 'B'
    },
    {
      name: 'cine-quiet-streets',
      label: 'Quiet Streets',
      file: 'themes/cinematic.css',
      swatch: '#92aed4'
    },
    {
      name: 'cine-cafe',
      label: 'Midnight Café',
      file: 'themes/cinematic.css',
      swatch: '#E9A85B',
      group: 'abc-wide-news',
      groupLabel: 'A/B: mesmo `wide`, mesma Newsreader — 34px/400/1.34 vs 32px/300/1.4',
      variant: 'A'
    },
    {
      name: 'cine-tideline',
      label: 'Tideline',
      file: 'themes/cinematic.css',
      swatch: '#9CC3CC',
      group: 'abc-wide-news',
      variant: 'B'
    },
    {
      name: 'cine-rainglass',
      label: 'Rainglass',
      file: 'themes/cinematic.css',
      swatch: '#9FC4D8',
      group: 'abc-tight-inter',
      groupLabel: 'A/B: mesmo `tight`, Inter 300 + caret — hairline vs folha clara',
      variant: 'A'
    },
    {
      name: 'cine-fieldnotes',
      label: 'Field Notes',
      file: 'themes/cinematic.css',
      swatch: '#A9CBC6',
      group: 'abc-tight-inter',
      variant: 'B'
    },
    {
      name: 'cine-dustlight',
      label: 'Dustlight',
      file: 'themes/cinematic.css',
      swatch: '#F09A55',
      group: 'abc-italic-serif',
      groupLabel: 'A/B: mesmo `italic`, 1.42 e -0.008em — Fraunces 33 vs Lora 30',
      variant: 'A'
    },
    {
      name: 'cine-rooftop',
      label: 'Rooftop Dusk',
      file: 'themes/cinematic.css',
      swatch: '#E4B0CC',
      group: 'abc-italic-serif',
      variant: 'B'
    },
    {
      name: 'cine-analog',
      label: 'Analog',
      file: 'themes/cinematic.css',
      swatch: '#DCB183'
    },
    {
      name: 'cine-shelves',
      label: 'Quiet Shelves',
      file: 'themes/cinematic.css',
      swatch: '#D8B060',
      group: 'abc-editorial',
      groupLabel: 'A/B: mesmo `editorial` à esquerda, 1.38 e -0.01em — Lora 31 vs Fraunces 32',
      variant: 'A'
    },
    {
      name: 'cine-ember',
      label: 'Ember',
      file: 'themes/cinematic.css',
      swatch: '#F08A4B',
      group: 'abc-editorial',
      variant: 'B'
    },
    {
      name: 'cine-rainline',
      label: 'Rainline',
      file: 'themes/cinematic.css',
      swatch: '#9fc9dd',
      group: 'abc-bare-center',
      groupLabel: 'A/B: mesmo `bare` ao centro, Manrope 300/1.42 vs Inter 300/1.46 — `sheet` + 46 riscos de chuva vs `rail` sem partículas',
      variant: 'A'
    },
    {
      name: 'cine-blue-hour',
      label: 'Blue Hour',
      file: 'themes/cinematic.css',
      swatch: '#e0a894',
      group: 'abc-bare-center',
      variant: 'B'
    },
    {
      name: 'cine-cellar',
      label: 'Cellar Sessions',
      file: 'themes/cinematic.css',
      swatch: '#d9a94f',
      group: 'abc-glass',
      groupLabel: 'A/B: mesmo painel `glass` com `blur(var(--blur)) saturate(1.15)` — roman 18px/.46 vs itálico 22px/.5',
      variant: 'A'
    },
    {
      name: 'cine-linen',
      label: 'Linen Hours',
      file: 'themes/cinematic.css',
      swatch: '#a8672f',
      group: 'abc-plate',
      groupLabel: 'A/B: mesmo painel `plate` com trilho à esquerda — escuro 18px/.46 vs papel claro 18px/.9',
      variant: 'A'
    },
    {
      name: 'cine-reading-hour',
      label: 'Reading Hour',
      file: 'themes/cinematic.css',
      swatch: '#c9a447',
      group: 'abc-chip',
      groupLabel: 'A/B: mesma `chip` ao centro, peso 400 — Lora 1.46/1.44 escuro vs Newsreader 1.44/1.44 claro',
      variant: 'A'
    },
    {
      name: 'cine-last-train',
      label: 'Last Train',
      file: 'themes/cinematic.css',
      swatch: '#a9c4a0',
      group: 'abc-stack',
      groupLabel: 'A/B: o mesmo `stack` de duas linhas — peso 300 sage vs 400 âmbar (fireside NÃO embarcado, ver §4)',
      variant: 'A'
    }
  ];
  var api = {
    themes: THEMES,
    /* The theme a document wears before anybody has chosen one. It is spelled
     * out here so `theme-switcher.js` and the harness cannot disagree about it. */
    fallback: 'theme-1',
    byName: function (name) {
      for (var i = 0; i < THEMES.length; i += 1) {
        if (THEMES[i].name === name) return THEMES[i];
      }
      return null;
    }
  };

  if (root) root.SottoThemeManifest = api;
  /* Also usable from Node (`node --check`, a manifest oracle), where there is no
   * `window` to hang it on. */
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
}(typeof window !== 'undefined' ? window : null));
